name = "PkgEval"
uuid = "9f2e2246-6dce-11e8-3d98-4b291446da6e"
authors = ["Keno Fischer <keno@juliacomputing.com>", "Tim Besard <tim@juliacomputing.com>"]
version = "0.1.0"

[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sandbox = "9307e30f-c43e-9ca7-d17c-c2dc59df670d"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
BinaryBuilder = "0.4"
DataFrames = "1.0"
Downloads = "1.0"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
